# Generated by Django 5.0.7 on 2025-01-13 17:43

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpage_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
